### ISSUE TITLE
Google classroom trainee tracker

### ISSUE THREAD

**Issue by SallyMcGrath** [SallyMcGrath/todo#1]
Goal: compute missing coursework values as milestone factor in trainee tracker

**MVP**

- [ ] turn on advanced services
- [ ] populate new tab with coursework 
- [ ] show number of pieces of coursework missing on performance tab
- [ ] if pieces is greater than 10 record as missing milestone

**Already done**

- [ ] can pull coursework
- [ ] can show missing

**Problems to solve (MVP only)**

connect google classroom student to trainee tracker student (dropouts are removed from classroom but not tracker)
