### ISSUE TITLE
Trainee tracker milestone reporter

### ISSUE THREAD

**Issue by SallyMcGrath** [SallyMcGrath/todo#2]
Goal: communicate milestone progress to trainees on milestone days

**MVP**

- [ ]  get channel ids for running course
- [ ]  turn on Slack reporter function 
- [ ]  turn on time trigger

**Already done**

- [ ]  can compute class progress
- [ ]  can run automatically on milestone days
- [ ]  can email Slack

 
**Problems to solve (MVP only)**

security risk putting authentication details into App Script
